# Generated by Django 5.2.7 on 2025-12-04 05:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_addr",
                    models.CharField(
                        db_index=True,
                        help_text="Actual token contract address",
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "pair_addr",
                    models.CharField(help_text="Pair contract address", max_length=42),
                ),
                (
                    "token_create_ts",
                    models.DateTimeField(help_text="Token creation timestamp"),
                ),
                (
                    "lp_create_ts",
                    models.DateTimeField(help_text="Liquidity pool creation timestamp"),
                ),
                (
                    "pair_idx",
                    models.IntegerField(help_text="Token index in pair (0 or 1)"),
                ),
                (
                    "pair_type",
                    models.CharField(
                        help_text="Router type used by the pair", max_length=50
                    ),
                ),
                (
                    "token_creator_addr",
                    models.CharField(
                        blank=True,
                        help_text="Token creator address",
                        max_length=42,
                        null=True,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True, help_text="Token symbol", max_length=20, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Token name", max_length=100, null=True
                    ),
                ),
                (
                    "holder_cnt",
                    models.IntegerField(
                        blank=True, help_text="Total number of token holders", null=True
                    ),
                ),
            ],
            options={
                "db_table": "token_info",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_addr",
                    models.CharField(
                        db_index=True,
                        help_text="Analyzed token contract address",
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        help_text="Final scam score calculated after analysis"
                    ),
                ),
                (
                    "scam_types",
                    models.CharField(
                        help_text="Detected scam categories", max_length=100
                    ),
                ),
                (
                    "victim_insights",
                    models.TextField(help_text="Scam indicators found in analysis"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Analysis completion timestamp",
                    ),
                ),
            ],
            options={
                "db_table": "result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExitMlResult",
            fields=[
                (
                    "token_info",
                    models.OneToOneField(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="exit_ml_result",
                        serialize=False,
                        to="api.tokeninfo",
                    ),
                ),
                (
                    "probability",
                    models.FloatField(help_text="Exit scam probability (0-1)"),
                ),
                (
                    "threshold",
                    models.FloatField(
                        default=0.6047, help_text="Decision threshold from model"
                    ),
                ),
                (
                    "is_exit_scam",
                    models.BooleanField(help_text="True if probability >= threshold"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "exit_ml_result",
            },
        ),
        migrations.CreateModel(
            name="HoneypotDaResult",
            fields=[
                (
                    "token_info",
                    models.OneToOneField(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="honeypot_da_result",
                        serialize=False,
                        to="api.tokeninfo",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(help_text="Contract verified on Etherscan"),
                ),
                (
                    "buy_sell_result",
                    models.BooleanField(help_text="Buy and sell both successful"),
                ),
                (
                    "buy_sell_return_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Return rate percentage (0-100)",
                        null=True,
                    ),
                ),
                ("blacklist_result", models.BooleanField()),
                ("blacklist_confidence", models.CharField(max_length=10)),
                ("trading_suspend_result", models.BooleanField()),
                ("trading_suspend_confidence", models.CharField(max_length=10)),
                ("exterior_call_result", models.BooleanField()),
                ("exterior_call_confidence", models.CharField(max_length=10)),
                ("unlimited_mint_result", models.BooleanField()),
                ("unlimited_mint_confidence", models.CharField(max_length=10)),
                ("balance_manipulation_result", models.BooleanField()),
                ("balance_manipulation_confidence", models.CharField(max_length=10)),
                ("tax_manipulation_result", models.BooleanField()),
                ("tax_manipulation_confidence", models.CharField(max_length=10)),
                ("existing_holders_result", models.BooleanField()),
                ("existing_holders_confidence", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "honeypot_da_result",
            },
        ),
        migrations.CreateModel(
            name="HoneypotMlResult",
            fields=[
                (
                    "token_info",
                    models.OneToOneField(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="honeypot_ml_result",
                        serialize=False,
                        to="api.tokeninfo",
                    ),
                ),
                (
                    "is_honeypot",
                    models.BooleanField(help_text="Honeypot prediction result"),
                ),
                (
                    "probability",
                    models.FloatField(help_text="Honeypot probability (0-1)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        help_text="Risk level: CRITICAL/HIGH/MEDIUM/LOW/VERY_LOW",
                        max_length=20,
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(help_text="Decision threshold from model"),
                ),
                (
                    "top_contributing_features",
                    models.JSONField(
                        help_text="Top 5 contributing features with values and directions"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "honeypot_ml_result",
            },
        ),
        migrations.CreateModel(
            name="HoneypotProcessedData",
            fields=[
                (
                    "token_info",
                    models.OneToOneField(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="honeypot_processed",
                        serialize=False,
                        to="api.tokeninfo",
                    ),
                ),
                (
                    "token_addr",
                    models.CharField(help_text="Token contract address", max_length=42),
                ),
                ("total_buy_cnt", models.IntegerField()),
                ("total_sell_cnt", models.IntegerField()),
                ("total_owner_sell_cnt", models.IntegerField()),
                ("total_non_owner_sell_cnt", models.IntegerField()),
                ("imbalance_rate", models.FloatField()),
                ("total_windows", models.IntegerField()),
                ("windows_with_activity", models.IntegerField()),
                ("total_burn_events", models.IntegerField()),
                ("total_mint_events", models.IntegerField()),
                ("s_owner_count", models.IntegerField()),
                (
                    "total_sell_vol",
                    models.DecimalField(decimal_places=18, max_digits=78),
                ),
                (
                    "total_buy_vol",
                    models.DecimalField(decimal_places=18, max_digits=78),
                ),
                (
                    "total_owner_sell_vol",
                    models.DecimalField(decimal_places=18, max_digits=78),
                ),
                ("total_sell_vol_log", models.FloatField()),
                ("total_buy_vol_log", models.FloatField()),
                ("total_owner_sell_vol_log", models.FloatField()),
                ("liquidity_event_mask", models.IntegerField()),
                ("max_sell_share", models.FloatField()),
                ("unique_sellers", models.IntegerField()),
                ("unique_buyers", models.IntegerField()),
                ("consecutive_sell_block_windows", models.IntegerField()),
                ("total_sell_block_windows", models.IntegerField()),
                ("gini_coefficient", models.FloatField()),
                ("total_holders", models.IntegerField()),
                ("whale_count", models.IntegerField()),
                ("whale_total_pct", models.FloatField()),
                ("small_holders_pct", models.FloatField()),
                ("holder_balance_std", models.FloatField()),
                ("holder_balance_cv", models.FloatField()),
                ("hhi_index", models.FloatField()),
                ("inactive_token_flag", models.IntegerField()),
                ("whale_domination_ratio", models.FloatField()),
                ("whale_presence_flag", models.IntegerField()),
                ("few_holders_flag", models.IntegerField()),
                ("airdrop_like_flag", models.IntegerField()),
                ("concentrated_large_community_score", models.FloatField()),
                ("hhi_per_holder", models.FloatField()),
                ("whale_but_no_small_flag", models.IntegerField()),
            ],
            options={
                "db_table": "honeypot_processed_data",
            },
        ),
        migrations.CreateModel(
            name="ExitProcessedDataStatic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_ratio_realized_vol", models.FloatField(blank=True, null=True)),
                ("price_ratio_range", models.FloatField(blank=True, null=True)),
                (
                    "reserve_quote_realized_vol",
                    models.FloatField(blank=True, null=True),
                ),
                ("burn_ratio_all", models.FloatField(blank=True, null=True)),
                (
                    "reserve_quote_drawdown_global",
                    models.FloatField(blank=True, null=True),
                ),
                ("swap_share", models.FloatField(blank=True, null=True)),
                ("swaps_last5", models.FloatField(blank=True, null=True)),
                ("liquidity_age_days", models.FloatField(blank=True, null=True)),
                ("holder_cnt", models.IntegerField(blank=True, null=True)),
                (
                    "token_info",
                    models.ForeignKey(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_processed_static",
                        to="api.tokeninfo",
                    ),
                ),
            ],
            options={
                "db_table": "exit_processed_data_static",
            },
        ),
        migrations.CreateModel(
            name="ExitMlDetectStatic",
            fields=[
                (
                    "exit_ml_result",
                    models.OneToOneField(
                        db_column="exit_ml_result_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="detect_static",
                        serialize=False,
                        to="api.exitmlresult",
                    ),
                ),
                (
                    "feature_values",
                    models.JSONField(help_text="Top static feature values as JSON"),
                ),
            ],
            options={
                "db_table": "exit_ml_detect_static",
            },
        ),
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_addr",
                    models.CharField(
                        db_index=True,
                        help_text="Token address being analyzed",
                        max_length=42,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collecting_token", "Collecting Token Info"),
                            ("collecting_pair", "Collecting Pair Events"),
                            ("collecting_holder", "Collecting Holder Info"),
                            ("preprocessing", "Preprocessing"),
                            ("analyzing_honeypot_da", "Honeypot Dynamic Analysis"),
                            ("analyzing_honeypot_ml", "Honeypot ML Analysis"),
                            ("analyzing_exit_ml", "Exit Scam ML Analysis"),
                            ("aggregating", "Aggregating Results"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        help_text="Current processing step description",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_step", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "token_info",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to TokenInfo after collection",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="api.tokeninfo",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token_addr", "-created_at"],
                        name="analysis_jo_token_a_999a8f_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="analysis_jo_status_bc2820_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExitProcessedDataInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_time",
                    models.DateTimeField(help_text="Event occurrence timestamp"),
                ),
                (
                    "tx_hash",
                    models.CharField(help_text="Transaction hash", max_length=66),
                ),
                (
                    "delta_t_sec",
                    models.FloatField(help_text="Time difference from previous event"),
                ),
                (
                    "is_swap_event",
                    models.BooleanField(
                        help_text="1 if Swap event included, 0 otherwise"
                    ),
                ),
                (
                    "lp_total_supply",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        help_text="Current LP total supply",
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "reserve_base_drop_frac",
                    models.FloatField(
                        blank=True, help_text="Base token decrease rate", null=True
                    ),
                ),
                (
                    "reserve_quote",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="Current major token balance",
                        max_digits=38,
                    ),
                ),
                (
                    "reserve_quote_drop_frac",
                    models.FloatField(
                        blank=True, help_text="Major token decrease rate", null=True
                    ),
                ),
                (
                    "price_ratio",
                    models.FloatField(blank=True, help_text="Price ratio", null=True),
                ),
                (
                    "time_since_last_mint_sec",
                    models.FloatField(
                        blank=True,
                        help_text="Time elapsed since last Mint (seconds)",
                        null=True,
                    ),
                ),
                (
                    "lp_minted_amount_per_sec",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=38, null=True
                    ),
                ),
                (
                    "lp_burned_amount_per_sec",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=38, null=True
                    ),
                ),
                ("recent_mint_ratio_last10", models.FloatField(blank=True, null=True)),
                ("recent_mint_ratio_last20", models.FloatField(blank=True, null=True)),
                ("recent_burn_ratio_last10", models.FloatField(blank=True, null=True)),
                ("recent_burn_ratio_last20", models.FloatField(blank=True, null=True)),
                ("reserve_quote_drawdown", models.FloatField(blank=True, null=True)),
                (
                    "token_info",
                    models.ForeignKey(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_processed_instance",
                        to="api.tokeninfo",
                    ),
                ),
            ],
            options={
                "db_table": "exit_processed_data_instance",
                "ordering": ["token_info", "event_time"],
                "indexes": [
                    models.Index(
                        fields=["token_info", "event_time"],
                        name="exit_proces_token_a_8e0f94_idx",
                    ),
                    models.Index(
                        fields=["tx_hash"], name="exit_proces_tx_hash_8cc242_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HolderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holder_addr",
                    models.CharField(help_text="Holder wallet address", max_length=42),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="Token balance held by this address",
                        max_digits=78,
                    ),
                ),
                (
                    "rel_to_total",
                    models.CharField(
                        help_text="Percentage of total supply held", max_length=20
                    ),
                ),
                (
                    "token_info",
                    models.ForeignKey(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="api.tokeninfo",
                    ),
                ),
            ],
            options={
                "db_table": "holder_info",
                "ordering": ["-balance"],
                "indexes": [
                    models.Index(
                        fields=["token_info", "-balance"],
                        name="holder_info_token_a_948d23_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PairEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Event timestamp (ISO format)"
                    ),
                ),
                (
                    "block_number",
                    models.IntegerField(help_text="Block number of the transaction"),
                ),
                (
                    "tx_hash",
                    models.CharField(help_text="Transaction hash", max_length=66),
                ),
                (
                    "tx_from",
                    models.CharField(
                        help_text="Transaction sender address", max_length=42
                    ),
                ),
                (
                    "tx_to",
                    models.CharField(
                        help_text="Transaction recipient address", max_length=42
                    ),
                ),
                (
                    "evt_idx",
                    models.IntegerField(help_text="Event log index in transaction"),
                ),
                (
                    "evt_type",
                    models.CharField(
                        help_text="Event type (Mint, Burn, Sync, Swap, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "evt_log",
                    models.JSONField(help_text="Preprocessed event log in JSON format"),
                ),
                (
                    "lp_total_supply",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="Current LP total supply",
                        max_digits=78,
                    ),
                ),
                (
                    "token_info",
                    models.ForeignKey(
                        db_column="token_addr_idx",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pair_events",
                        to="api.tokeninfo",
                    ),
                ),
            ],
            options={
                "db_table": "pair_evt",
                "ordering": ["timestamp", "evt_idx"],
                "indexes": [
                    models.Index(
                        fields=["token_info", "timestamp"],
                        name="pair_evt_token_a_8294b9_idx",
                    ),
                    models.Index(
                        fields=["block_number"], name="pair_evt_block_n_7471a4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExitMlDetectTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(help_text="Transaction rank (1, 2, or 3)"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, help_text="Transaction timestamp", null=True
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash",
                        max_length=66,
                        null=True,
                    ),
                ),
                (
                    "feature_values",
                    models.JSONField(
                        help_text="Top instance feature values (scaled) as JSON"
                    ),
                ),
                (
                    "exit_ml_result",
                    models.ForeignKey(
                        db_column="exit_ml_result_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detect_transactions",
                        to="api.exitmlresult",
                    ),
                ),
            ],
            options={
                "db_table": "exit_ml_detect_transaction",
                "ordering": ["exit_ml_result", "rank"],
                "unique_together": {("exit_ml_result", "rank")},
            },
        ),
    ]
