# Generated by Django 5.2.7 on 2025-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokeninfo',
            name='holder_cnt',
            field=models.IntegerField(blank=True, help_text='Total number of token holders', null=True),
        ),
    ]
