# Generated by Django 5.2.7 on 2025-11-17 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotDaResult',
            fields=[
                ('token_info', models.OneToOneField(db_column='token_addr_idx', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='honeypot_da_result', serialize=False, to='api.tokeninfo')),
                ('verified', models.BooleanField(help_text='Contract verified on Etherscan')),
                ('buy_sell_result', models.BooleanField(help_text='Buy and sell both successful')),
                ('buy_sell_return_rate', models.FloatField(blank=True, help_text='Return rate percentage (0-100)', null=True)),
                ('blacklist_result', models.BooleanField()),
                ('blacklist_confidence', models.CharField(max_length=10)),
                ('trading_suspend_result', models.BooleanField()),
                ('trading_suspend_confidence', models.CharField(max_length=10)),
                ('exterior_call_result', models.BooleanField()),
                ('exterior_call_confidence', models.CharField(max_length=10)),
                ('unlimited_mint_result', models.BooleanField()),
                ('unlimited_mint_confidence', models.CharField(max_length=10)),
                ('balance_manipulation_result', models.BooleanField()),
                ('balance_manipulation_confidence', models.CharField(max_length=10)),
                ('tax_manipulation_result', models.BooleanField()),
                ('tax_manipulation_confidence', models.CharField(max_length=10)),
                ('existing_holders_result', models.BooleanField()),
                ('existing_holders_confidence', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'honeypot_da_result',
            },
        ),
        migrations.AddField(
            model_name='tokeninfo',
            name='contract_creator',
            field=models.CharField(blank=True, help_text='Token contract creator address (from Etherscan)', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='tokeninfo',
            name='pair_creator',
            field=models.CharField(blank=True, help_text='Liquidity pool creator address', max_length=42, null=True),
        ),
    ]
