# Generated by Django 5.2.7 on 2025-11-22 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_honeypotdaresult_tokeninfo_contract_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitMlResult',
            fields=[
                ('token_info', models.OneToOneField(db_column='token_addr_idx', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exit_ml_result', serialize=False, to='api.tokeninfo')),
                ('probability', models.FloatField(help_text='Exit scam probability (0-1)')),
                ('threshold', models.FloatField(default=0.6047, help_text='Decision threshold from model')),
                ('is_exit_scam', models.BooleanField(help_text='True if probability >= threshold')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'exit_ml_result',
            },
        ),
        migrations.CreateModel(
            name='ExitMlDetectStatic',
            fields=[
                ('exit_ml_result', models.OneToOneField(db_column='exit_ml_result_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detect_static', serialize=False, to='api.exitmlresult')),
                ('feature_values', models.JSONField(help_text='Top static feature values as JSON')),
            ],
            options={
                'db_table': 'exit_ml_detect_static',
            },
        ),
        migrations.CreateModel(
            name='ExitMlDetectTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Transaction rank (1, 2, or 3)')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Transaction timestamp', null=True)),
                ('tx_hash', models.CharField(blank=True, help_text='Transaction hash', max_length=66, null=True)),
                ('feature_values', models.JSONField(help_text='Top instance feature values (scaled) as JSON')),
                ('exit_ml_result', models.ForeignKey(db_column='exit_ml_result_id', on_delete=django.db.models.deletion.CASCADE, related_name='detect_transactions', to='api.exitmlresult')),
            ],
            options={
                'db_table': 'exit_ml_detect_transaction',
                'ordering': ['exit_ml_result', 'rank'],
                'unique_together': {('exit_ml_result', 'rank')},
            },
        ),
    ]
