# Generated by Django 5.2.7 on 2025-11-22 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exitmlresult_exitmldetectstatic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotMlResult',
            fields=[
                ('token_info', models.OneToOneField(db_column='token_addr_idx', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='honeypot_ml_result', serialize=False, to='api.tokeninfo')),
                ('is_honeypot', models.BooleanField(help_text='Honeypot prediction result')),
                ('probability', models.FloatField(help_text='Honeypot probability (0-1)')),
                ('risk_level', models.CharField(help_text='Risk level: CRITICAL/HIGH/MEDIUM/LOW/VERY_LOW', max_length=20)),
                ('threshold', models.FloatField(help_text='Decision threshold from model')),
                ('top_contributing_features', models.JSONField(help_text='Top 5 contributing features with values and directions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'honeypot_ml_result',
            },
        ),
    ]
