# Generated by Django 5.2.7 on 2025-11-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_honeypotmlresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairevent',
            name='reserve0',
        ),
        migrations.RemoveField(
            model_name='pairevent',
            name='reserve1',
        ),
        migrations.RemoveField(
            model_name='pairevent',
            name='token0',
        ),
        migrations.RemoveField(
            model_name='pairevent',
            name='token1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='token_info',
        ),
        migrations.RemoveField(
            model_name='tokeninfo',
            name='contract_creator',
        ),
        migrations.RemoveField(
            model_name='tokeninfo',
            name='pair_creator',
        ),
        migrations.AddField(
            model_name='tokeninfo',
            name='token_creator_addr',
            field=models.CharField(blank=True, help_text='Token creator address', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='scam_types',
            field=models.CharField(help_text='Detected scam categories', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='victim_insights',
            field=models.TextField(help_text='Scam indicators found in analysis'),
        ),
    ]
